# Generated by Django 5.2.17 on 2026-10-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_initial', models.CharField(max_length=5)),
                ('course', models.CharField(max_length=100)),
                ('year_level', models.IntegerField()),
                ('section', models.CharField(max_length=10)),
            ],
        ),
    ]
